
'use server';
/**
 * @fileOverview A RAG-enabled chatbot advisory AI agent for farmers.
 *
 * - provideChatbotAdvisory - A function that handles the chatbot advisory process.
 * - ProvideChatbotAdvisoryInput - The input type for the provideChatbotAdvisory function.
 * - ProvideChatbotAdvisoryOutput - The return type for the provideChatbotAdvisory function.
 */

import { analyzeLocalDiseaseImage, getLocalChatAdvice } from '@/lib/local-ai-client';
import {z} from 'zod';

const ChatHistorySchema = z.object({
    role: z.enum(['user', 'assistant']),
    text: z.string(),
});

const ProvideChatbotAdvisoryInputSchema = z.object({
  query: z.string().describe('The query from the farmer.'),
  managementType: z.enum(['Crops', 'Fruits']).describe('The management context (Crops or Fruits).'),
  photoDataUri: z
    .string()
    .optional()
    .describe(
      "An optional photo provided by the user, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  documentContent: z
    .string()
    .optional()
    .describe("Optional text content from a user-uploaded document."),
  history: z.array(ChatHistorySchema).optional().describe('The entire previous conversation history for context.'),
  language: z.string().optional().describe("The user's preferred language (e.g., 'en', 'hi')."),
});
export type ProvideChatbotAdvisoryInput = z.infer<typeof ProvideChatbotAdvisoryInputSchema>;

const ProvideChatbotAdvisoryOutputSchema = z.object({
  advice: z.string().describe('The advice generated by the chatbot.'),
});
export type ProvideChatbotAdvisoryOutput = z.infer<typeof ProvideChatbotAdvisoryOutputSchema>;

export async function provideChatbotAdvisory(input: ProvideChatbotAdvisoryInput): Promise<ProvideChatbotAdvisoryOutput> {
  return provideChatbotAdvisoryFlow(input);
}

async function provideChatbotAdvisoryFlow(
  input: ProvideChatbotAdvisoryInput
): Promise<ProvideChatbotAdvisoryOutput> {
  let imageContext = '';

  if (input.photoDataUri) {
    try {
      const diseaseResult = await analyzeLocalDiseaseImage({
        photoDataUri: input.photoDataUri,
        itemType: input.managementType === 'Fruits' ? 'Fruit' : 'Crop',
        language: input.language,
      });
      imageContext =
        `Image analysis result: ${diseaseResult.diseaseName}, confidence ${Math.round(diseaseResult.confidenceLevel * 100)}%. ` +
        `Suggested treatment: ${diseaseResult.suggestedSolutions}`;
    } catch (error) {
      console.warn('Image analysis failed inside chatbot flow:', error);
      imageContext = 'Image was attached, but local image analysis failed.';
    }
  }

  const documentContent = [input.documentContent, imageContext].filter(Boolean).join('\n\n');

  const output = await getLocalChatAdvice({
    query: input.query,
    managementType: input.managementType,
    history: input.history,
    documentContent: documentContent || undefined,
    language: input.language,
  });

  return ProvideChatbotAdvisoryOutputSchema.parse(output);
}
